### PR TITLE
Version updates, Refactor, and new property to control the video Fit ❤

### PR DESCRIPTION
**Pull request by moazelsawaf**
Hello

Dear @takumade,

In the Pull Request, I have updated the versions of Dart SDK and used Packages in both the package and the example, migrated the Android project in the example to the new flutter embedding, refactored the package and the example with linting, enhanced the UI of loading widget before the `BetterPlayerController` gets initialized, and lastly added a new property called `fullscreenVideoFit` to control the Fit of the video in Full Screen mode in order to solve the stretching problem in the full screen.

I hope you enjoy the contribution ❤

Thanks,
Moaz El-sawaf

### CODE REVIEW

**Comment by moazelsawaf** [comment]
@takumade 
Can you please review this PR? ❤

**Review by phoscoder — APPROVED** [review]
Looks good to me, Thank you very much

**Comment by moazelsawaf** [comment]
You're always welcome ❤️

**Comment by moazelsawaf** [comment]
Mr. @takumade I just wanted to ask you why the `READ.ME` file is not synced with the [package page](https://pub.dev/packages/vimeoplayer_trinity) in [pub.dev](https://pub.dev/)?

I want to contribute in the documentation of the package but I am afraid that you change it from some where else, so how can I do that?

Thanks in advance.

**Comment by phoscoder** [comment]
Mr @moazelsawaf please make a pull request then i will push the new changes to pub.dev

**Comment by moazelsawaf** [comment]
Great, will do Insh'Allah ❤️

**Comment by phoscoder** [comment]
ok

**Pull request merged**
